image: golang:1.20

stages:
  - build
  - test
  - dependency

build:
  tags:
    - iam_ci
  stage: build
  script:
    - go build

test:
  tags:
    - iam_ci
  stage: test
  script:
    - apt update
    - apt install -y libssl-dev softhsm2
    - cp ./ci/rootCA.crt.pem  /etc/ssl/certs/
    - go test $(go list ./... | grep -v "/vendor") -v -coverprofile .testCoverage.txt
    - go tool cover -func=.testCoverage.txt

whitesource:
  only:
    refs:
      - master
      - develop
  tags:
    - whitesource_ci
  stage: dependency
  script:
    - java -jar /usr/bin/wss-unified-agent.jar -apiKey $WSS_API_KEY -projectToken $WSS_IAM_TOKEN -userKey $WSS_USER_KEY  -c ./ci/wss-iam.conf -d ./ -scanComment $CI_COMMIT_SHORT_SHA
